-- cloudflare-worker/schema.sql
--
-- ⚠️  THIS FILE IS SUPERSEDED by the migrations directory.
--
-- The canonical schema is now managed via Wrangler D1 migrations:
--   cloudflare-worker/migrations/0001_init.sql
--
-- To initialise or update the database, run:
--   cd cloudflare-worker
--   npx wrangler d1 migrations apply tradingbot --remote
--
-- DO NOT run this file directly.  It is kept only for historical reference.
-- The migration files use CREATE TABLE IF NOT EXISTS and INSERT OR IGNORE,
-- making them safe to re-run without destroying existing data.
